# Build settings
markdown: kramdown
baseurl: "/joe-and-kelly-wedding"

# your site URL goes here
# url: ""

port: 4000
exclude:
  - dev_assets
  - node_modules
  - package.json
  - gulpfile.js
  - README.md
  - config
  - npm-debug.log