# Build settings
markdown: kramdown
baseurl: ""

# your site URL goes here
url: "http://mmcbride1007.github.io/joe-and-kelly-wedding"

port: 4000
exclude:
  - dev_assets
  - node_modules
  - package.json
  - gulpfile.js
  - README.md
  - config
